# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

"""
AIPerf Configuration v2.0 - YAML Configuration System

This package provides a complete, from-scratch implementation of the AIPerf
YAML configuration system. It is designed to support all 150+ configuration
options while providing a clean, composable, and well-documented API.

Key Features:
    - Named datasets with composition and augmentation
    - Multi-phase benchmark configuration with seamless transitions
    - ISL/OSL distributions for realistic workload modeling
    - Comprehensive multimodal support (images, audio, video)
    - SLO-based goodput tracking
    - Environment variable substitution
    - Full Pydantic validation with detailed error messages

Example Usage:
    >>> from config_v2 import load_config, AIPerfConfig
    >>> config = load_config("benchmark.yaml")
    >>> print(config.models)
    >>> print(config.phases[0].name)

    Or programmatically:
    >>> from config_v2 import AIPerfConfig
    >>> config = AIPerfConfig(
    ...     models=["llama-3-8b"],
    ...     endpoint={"urls": ["http://localhost:8000/v1/chat/completions"]},
    ...     datasets={"main": {"type": "synthetic", "count": 1000}},
    ...     phases=[{"name": "profiling", "dataset": "main", "concurrency": 8}]
    ... )

Schema Version: 2.0.0
"""

########################################################################
## 🚩                     mkinit flags                             🚩 ##
########################################################################
__ignore__ = []
########################################################################
## ⚠️       This file is auto-generated by `make init-files`       ⚠️ ##
## ⚠️                Do not edit below this line                   ⚠️ ##
########################################################################
from aiperf.config.artifacts import (
    ArtifactsConfig,
    GpuTelemetryConfig,
    ServerMetricsConfig,
)
from aiperf.config.cli_builder import (
    CLIModel,
    build_aiperf_config,
)
from aiperf.config.cli_mapping import (
    CLIField,
    CLIGroup,
)
from aiperf.config.config import (
    AIPerfConfig,
)
from aiperf.config.constraints import (
    AllOrNone,
    AtLeastOne,
    AtLeastOneTruthy,
    AtLeastOneUnless,
    BaseComparisonConstraint,
    BaseConstraint,
    CompareTo,
    ComparisonOp,
    ConflictsWith,
    ConstraintGroup,
    Constraints,
    ConstraintsError,
    ConstraintsMixin,
    ConstraintType,
    ConstraintViolation,
    ExactlyOne,
    ExactlyOneTruthy,
    ExclusiveGroup,
    F,
    FieldCountRange,
    ForbiddenWith,
    ForbiddenWithIn,
    Forbids,
    ForbidsIfTruthy,
    GreaterThan,
    GreaterThanOrEqual,
    GroupConflictsWith,
    LessThan,
    LessThanOrEqual,
    Matches,
    MaxFieldsSet,
    MinFieldsSet,
    NotEqualTo,
    RequiredIf,
    RequiredIfIn,
    Requires,
    RequiresAllOf,
    RequiresAnyOf,
    RequiresIfTruthy,
    TruthyExclusiveGroup,
    ValidationContext,
    collect_cli_to_field_mapping,
    collect_constraints,
    collect_field_display_names,
    wired_constraints,
)
from aiperf.config.dataset import (
    AudioConfig,
    AugmentConfig,
    AugmentPrefixConfig,
    AugmentSuffixConfig,
    AugmentTextConfig,
    ComposedDataset,
    DatasetConfig,
    FileDataset,
    FileSourceConfig,
    ImageConfig,
    PrefixPromptConfig,
    PromptConfig,
    PublicDataset,
    RankingsConfig,
    SynthesisConfig,
    SyntheticDataset,
    VideoConfig,
)
from aiperf.config.endpoint import (
    EndpointConfig,
    TemplateConfig,
)
from aiperf.config.loader import (
    ENV_VAR_PATTERN,
    ConfigurationError,
    MissingEnvironmentVariableError,
    dump_config,
    load_config,
    load_config_from_string,
    merge_configs,
    save_config,
    substitute_env_vars,
    validate_config_file,
)
from aiperf.config.models import (
    CommunicationConfig,
    DualBindCommunicationConfig,
    IpcCommunicationConfig,
    LoggingConfig,
    ModelItem,
    ModelsAdvanced,
    RuntimeConfig,
    SLOsConfig,
    TcpCommunicationConfig,
    TcpProxyConfig,
    TokenizerConfig,
    TokenizerOverride,
)
from aiperf.config.phases import (
    CancellationConfig,
    PhaseConfig,
    PhaseType,
    PhaseTypeStr,
    RampConfig,
)
from aiperf.config.types import (
    MeanStddev,
    SequenceDistributionEntry,
    validate_probability_distribution,
)

__all__ = [
    "AIPerfConfig",
    "AllOrNone",
    "ArtifactsConfig",
    "AtLeastOne",
    "AtLeastOneTruthy",
    "AtLeastOneUnless",
    "AudioConfig",
    "AugmentConfig",
    "AugmentPrefixConfig",
    "AugmentSuffixConfig",
    "AugmentTextConfig",
    "BaseComparisonConstraint",
    "BaseConstraint",
    "CLIField",
    "CLIGroup",
    "CLIModel",
    "CancellationConfig",
    "CommunicationConfig",
    "CompareTo",
    "ComparisonOp",
    "ComposedDataset",
    "ConfigurationError",
    "ConflictsWith",
    "ConstraintGroup",
    "ConstraintType",
    "ConstraintViolation",
    "Constraints",
    "ConstraintsError",
    "ConstraintsMixin",
    "DatasetConfig",
    "DualBindCommunicationConfig",
    "ENV_VAR_PATTERN",
    "EndpointConfig",
    "ExactlyOne",
    "ExactlyOneTruthy",
    "ExclusiveGroup",
    "F",
    "FieldCountRange",
    "FileDataset",
    "FileSourceConfig",
    "ForbiddenWith",
    "ForbiddenWithIn",
    "Forbids",
    "ForbidsIfTruthy",
    "GpuTelemetryConfig",
    "GreaterThan",
    "GreaterThanOrEqual",
    "GroupConflictsWith",
    "ImageConfig",
    "IpcCommunicationConfig",
    "LessThan",
    "LessThanOrEqual",
    "LoggingConfig",
    "Matches",
    "MaxFieldsSet",
    "MeanStddev",
    "MinFieldsSet",
    "MissingEnvironmentVariableError",
    "ModelItem",
    "ModelsAdvanced",
    "NotEqualTo",
    "PhaseConfig",
    "PhaseType",
    "PhaseTypeStr",
    "PrefixPromptConfig",
    "PromptConfig",
    "PublicDataset",
    "RampConfig",
    "RankingsConfig",
    "RequiredIf",
    "RequiredIfIn",
    "Requires",
    "RequiresAllOf",
    "RequiresAnyOf",
    "RequiresIfTruthy",
    "RuntimeConfig",
    "SLOsConfig",
    "SequenceDistributionEntry",
    "ServerMetricsConfig",
    "SynthesisConfig",
    "SyntheticDataset",
    "TcpCommunicationConfig",
    "TcpProxyConfig",
    "TemplateConfig",
    "TokenizerConfig",
    "TokenizerOverride",
    "TruthyExclusiveGroup",
    "ValidationContext",
    "VideoConfig",
    "collect_cli_to_field_mapping",
    "collect_constraints",
    "collect_field_display_names",
    "build_aiperf_config",
    "dump_config",
    "load_config",
    "load_config_from_string",
    "merge_configs",
    "save_config",
    "substitute_env_vars",
    "validate_config_file",
    "validate_probability_distribution",
    "wired_constraints",
]
