# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

from aiperf.common.enums import GenericMetricUnit, MetricFlags
from aiperf.common.exceptions import NoMetricValue
from aiperf.common.models import ParsedResponseRecord
from aiperf.metrics import BaseRecordMetric
from aiperf.metrics.derived_sum_metric import DerivedSumMetric
from aiperf.metrics.metric_dicts import MetricRecordDict


class OutputTokenCountMetric(BaseRecordMetric[int]):
    """
    Post-processor for calculating Output Token Count metrics from records.

    This is the total number of output tokens generated by the model for one
    individual record. Prefers server-reported ``token_counts.output``, falling
    back to client-side ``token_counts.output_local``.

    Formula:
        Output Token Count = Sum(Output Token Counts)
    """

    tag = "output_token_count"
    header = "Output Token Count"
    short_header = "Output Tokens"
    short_header_hide_unit = True
    unit = GenericMetricUnit.TOKENS
    flags = (
        MetricFlags.PRODUCES_TOKENS_ONLY
        | MetricFlags.LARGER_IS_BETTER
        | MetricFlags.NO_CONSOLE
    )
    required_metrics = None

    def _parse_record(
        self,
        record: ParsedResponseRecord,
        record_metrics: MetricRecordDict,
    ) -> int:
        """
        This method extracts the output token count from the record and returns it.

        Prefers server-reported output, falls back to output_local.

        Raises:
            NoMetricValue: If the record does not have an output token count.
        """
        if record.token_counts is None:
            raise NoMetricValue("Output token count is missing in the record.")

        if record.token_counts.output is not None:
            return record.token_counts.output

        if record.token_counts.output_local is not None:
            return record.token_counts.output_local

        raise NoMetricValue("Output token count is missing in the record.")


class OutputTokenCountServerMetric(BaseRecordMetric[int]):
    """
    Server-reported Output Token Count — file-only metric.

    Returns the server-reported output token count (``token_counts.output``).
    Raises ``NoMetricValue`` when the server did not report a value.
    """

    tag = "output_token_count_server"
    header = "Output Token Count (Server)"
    short_header = "Output Server"
    short_header_hide_unit = True
    unit = GenericMetricUnit.TOKENS
    flags = (
        MetricFlags.PRODUCES_TOKENS_ONLY
        | MetricFlags.LARGER_IS_BETTER
        | MetricFlags.NO_CONSOLE
    )
    required_metrics = None

    def _parse_record(
        self,
        record: ParsedResponseRecord,
        record_metrics: MetricRecordDict,
    ) -> int:
        if record.token_counts is not None and record.token_counts.output is not None:
            return record.token_counts.output
        raise NoMetricValue("Server-reported output token count is not available.")


class OutputTokenCountLocalMetric(BaseRecordMetric[int]):
    """
    Client-side tokenized Output Token Count — file-only metric.

    Returns the client-side tokenized output token count
    (``token_counts.output_local``). Raises ``NoMetricValue`` when the
    client-side value is not available.
    """

    tag = "output_token_count_local"
    header = "Output Token Count (Local)"
    short_header = "Output Local"
    short_header_hide_unit = True
    unit = GenericMetricUnit.TOKENS
    flags = (
        MetricFlags.PRODUCES_TOKENS_ONLY
        | MetricFlags.LARGER_IS_BETTER
        | MetricFlags.NO_CONSOLE
    )
    required_metrics = None

    def _parse_record(
        self,
        record: ParsedResponseRecord,
        record_metrics: MetricRecordDict,
    ) -> int:
        if (
            record.token_counts is not None
            and record.token_counts.output_local is not None
        ):
            return record.token_counts.output_local
        raise NoMetricValue("Client-side output token count is not available.")


class TotalOutputTokensMetric(DerivedSumMetric[int, OutputTokenCountMetric]):
    """
    This is the total number of output tokens generated by the model for
    all records.

    Formula:
        ```
        Total Output Tokens = Sum(Output Token Counts)
        ```
    """

    tag = "total_output_tokens"
    header = "Total Output Tokens"
    short_header = "Total Output"
    short_header_hide_unit = True
    flags = (
        MetricFlags.PRODUCES_TOKENS_ONLY
        | MetricFlags.LARGER_IS_BETTER
        | MetricFlags.NO_CONSOLE
    )
