# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

from aiperf.common.enums import GenericMetricUnit, MetricFlags
from aiperf.common.exceptions import NoMetricValue
from aiperf.common.models import ParsedResponseRecord
from aiperf.metrics import BaseRecordMetric
from aiperf.metrics.derived_sum_metric import DerivedSumMetric
from aiperf.metrics.metric_dicts import MetricRecordDict


class OutputSequenceLengthMetric(BaseRecordMetric[int]):
    """
    Post-processor for calculating Output Sequence Length (OSL) metrics from records.

    This is the total number of tokens generated by the model for one individual record.
    It is sometimes referred to as "Completion Token Count". It includes both reasoning and
    output tokens.

    Formula:
        Output Sequence Length = Output Token Count + Reasoning Token Count
    """

    tag = "output_sequence_length"
    header = "Output Sequence Length"
    short_header = "OSL"
    unit = GenericMetricUnit.TOKENS
    display_order = 600
    flags = MetricFlags.PRODUCES_TOKENS_ONLY | MetricFlags.LARGER_IS_BETTER
    required_metrics = None

    def _parse_record(
        self,
        record: ParsedResponseRecord,
        record_metrics: MetricRecordDict,
    ) -> int:
        """
        This method extracts the output and reasoning token counts from the record and returns the sum.

        Uses a consistent source for both components to avoid mixing server and
        client counts (which can double-count when the server's completion_tokens
        already includes reasoning tokens but doesn't break them out separately).

        Raises:
            NoMetricValue: If neither server nor local values are available for both components.
        """
        if record.token_counts is None:
            raise NoMetricValue(
                "Output and reasoning token counts are missing in the record."
            )

        tc = record.token_counts
        server_output = tc.output
        server_reasoning = tc.reasoning

        if server_output is not None and server_reasoning is not None:
            output = server_output
            reasoning = server_reasoning
        elif tc.output_local is not None:
            # Server didn't report both components — use all-client to avoid
            # mixing sources (server output may already include reasoning).
            output = tc.output_local
            reasoning = tc.reasoning_local
        else:
            # No client-local available either — use whatever we have
            output = server_output
            reasoning = server_reasoning

        if output is None and reasoning is None:
            raise NoMetricValue(
                "Output and reasoning token counts are missing in the record."
            )

        return (output or 0) + (reasoning or 0)


class TotalOutputSequenceLengthMetric(
    DerivedSumMetric[int, OutputSequenceLengthMetric]
):
    """
    This is the total number of completion tokens processed by the benchmark.

    Formula:
        ```
        Total Output Sequence Length = Sum(Output Sequence Lengths)
        ```
    """

    tag = "total_osl"
    header = "Total Output Sequence Length"
    short_header = "Total OSL"
    short_header_hide_unit = True
    flags = (
        MetricFlags.PRODUCES_TOKENS_ONLY
        | MetricFlags.LARGER_IS_BETTER
        | MetricFlags.NO_CONSOLE
    )
