# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

from aiperf.common.enums import GenericMetricUnit, MetricFlags
from aiperf.common.exceptions import NoMetricValue
from aiperf.common.models import ParsedResponseRecord
from aiperf.metrics import BaseRecordMetric
from aiperf.metrics.derived_sum_metric import DerivedSumMetric
from aiperf.metrics.metric_dicts import MetricRecordDict


class ReasoningTokenCountMetric(BaseRecordMetric[int]):
    """
    Post-processor for calculating Reasoning Token Count metrics from records.

    This is the total number of reasoning tokens generated by the model for
    one individual record. Prefers server-reported ``token_counts.reasoning``,
    falling back to client-side ``token_counts.reasoning_local``.

    Formula:
        ```
        Reasoning Token Count = Sum(Reasoning Tokens)
        ```
    """

    tag = "reasoning_token_count"
    header = "Reasoning Token Count"
    short_header = "Reasoning Tokens"
    short_header_hide_unit = True
    unit = GenericMetricUnit.TOKENS
    flags = (
        MetricFlags.PRODUCES_TOKENS_ONLY
        | MetricFlags.LARGER_IS_BETTER
        | MetricFlags.SUPPORTS_REASONING
        | MetricFlags.NO_CONSOLE
    )
    required_metrics = None

    def _parse_record(
        self,
        record: ParsedResponseRecord,
        record_metrics: MetricRecordDict,
    ) -> int:
        """
        This method extracts the reasoning token count from the record and returns it.

        Prefers server-reported reasoning, falls back to reasoning_local.

        Raises:
            NoMetricValue: If the record does not have a reasoning token count.
        """
        if record.token_counts is None:
            raise NoMetricValue("Reasoning token count is missing in the record.")

        if record.token_counts.reasoning is not None:
            return record.token_counts.reasoning

        if record.token_counts.reasoning_local is not None:
            return record.token_counts.reasoning_local

        raise NoMetricValue("Reasoning token count is missing in the record.")


class ReasoningTokenCountServerMetric(BaseRecordMetric[int]):
    """
    Server-reported Reasoning Token Count — file-only metric.

    Returns the server-reported reasoning token count (``token_counts.reasoning``).
    Raises ``NoMetricValue`` when the server did not report a value.
    """

    tag = "reasoning_token_count_server"
    header = "Reasoning Token Count (Server)"
    short_header = "Reasoning Server"
    short_header_hide_unit = True
    unit = GenericMetricUnit.TOKENS
    flags = (
        MetricFlags.PRODUCES_TOKENS_ONLY
        | MetricFlags.LARGER_IS_BETTER
        | MetricFlags.SUPPORTS_REASONING
        | MetricFlags.NO_CONSOLE
    )
    required_metrics = None

    def _parse_record(
        self,
        record: ParsedResponseRecord,
        record_metrics: MetricRecordDict,
    ) -> int:
        if (
            record.token_counts is not None
            and record.token_counts.reasoning is not None
        ):
            return record.token_counts.reasoning
        raise NoMetricValue("Server-reported reasoning token count is not available.")


class ReasoningTokenCountLocalMetric(BaseRecordMetric[int]):
    """
    Client-side tokenized Reasoning Token Count — file-only metric.

    Returns the client-side tokenized reasoning token count
    (``token_counts.reasoning_local``). Raises ``NoMetricValue`` when the
    client-side value is not available.
    """

    tag = "reasoning_token_count_local"
    header = "Reasoning Token Count (Local)"
    short_header = "Reasoning Local"
    short_header_hide_unit = True
    unit = GenericMetricUnit.TOKENS
    flags = (
        MetricFlags.PRODUCES_TOKENS_ONLY
        | MetricFlags.LARGER_IS_BETTER
        | MetricFlags.SUPPORTS_REASONING
        | MetricFlags.NO_CONSOLE
    )
    required_metrics = None

    def _parse_record(
        self,
        record: ParsedResponseRecord,
        record_metrics: MetricRecordDict,
    ) -> int:
        if (
            record.token_counts is not None
            and record.token_counts.reasoning_local is not None
        ):
            return record.token_counts.reasoning_local
        raise NoMetricValue("Client-side reasoning token count is not available.")


class TotalReasoningTokensMetric(DerivedSumMetric[int, ReasoningTokenCountMetric]):
    """
    This is the total number of reasoning tokens generated by the model for
    all records.

    Formula:
        ```
        Total Reasoning Tokens = Sum(Reasoning Tokens)
        ```
    """

    tag = "total_reasoning_tokens"
    header = "Total Reasoning Tokens"
    short_header = "Total Reasoning"
    short_header_hide_unit = True
    flags = (
        MetricFlags.PRODUCES_TOKENS_ONLY
        | MetricFlags.LARGER_IS_BETTER
        | MetricFlags.NO_CONSOLE
    )
