apiVersion: aiperf.nvidia.com/v1alpha1
kind: AIPerfJob
metadata:
  name: deepseek-r1-bench
spec:
  benchmark:
    models:
    - deepseek-ai/DeepSeek-R1
    endpoint:
      urls:
      - http://trtllm-disagg-multinode-frontend:8000
      type: chat
      streaming: true
      path: /v1/chat/completions
      extra:
        max_tokens: 1024
        min_tokens: 1024
        ignore_eos: true
        repetition_penalty: 1.0
        temperature: 0.0
        nvext:
          ignore_eos: true
      headers:
        Authorization: Bearer NOT USED
        Accept: text/event-stream
    tokenizer:
      name: /model-cache/deepseek-r1-fp4
    datasets:
      main:
        type: synthetic
        entries: 12800
        isl:
          mean: 1024
          stddev: 0
        osl:
          mean: 1024
          stddev: 0
    warmup:
      type: concurrency
      concurrency: 1080
      requests: 1080
    profiling:
      type: concurrency
      concurrency: 1080
      requests: 10800
    random_seed: 100
  podTemplate:
    imagePullSecrets:
    - nvcrimagepullsecret
    env:
    - name: AIPERF_HTTP_CONNECTION_LIMIT
      value: '252'
    volumes:
    - name: model-cache
      persistentVolumeClaim:
        claimName: model-cache
    volumeMounts:
    - name: model-cache
      mountPath: /model-cache
