apiVersion: aiperf.nvidia.com/v1alpha1
kind: AIPerfJob
metadata:
  name: llama3-70b-disagg-mn-perf
spec:
  benchmark:
    models:
    - RedHatAI/Llama-3.3-70B-Instruct-FP8-dynamic
    endpoint:
      urls:
      - http://llama3-70b-disagg-mn-frontend:8000
      type: chat
      streaming: true
      path: /v1/chat/completions
      extra:
        max_tokens: 1024
        min_tokens: 1024
        ignore_eos: true
        repetition_penalty: 1.0
        temperature: 0.0
        nvext:
          ignore_eos: true
      headers:
        Authorization: Bearer NOT USED
        Accept: text/event-stream
    tokenizer:
      name: RedHatAI/Llama-3.3-70B-Instruct-FP8-dynamic
    datasets:
      main:
        type: synthetic
        entries: 12800
        isl:
          mean: 8192
          stddev: 0
        osl:
          mean: 1024
          stddev: 0
    warmup:
      type: concurrency
      concurrency: 256
      requests: 256
    profiling:
      type: concurrency
      concurrency: 256
      requests: 2560
    random_seed: 100
  podTemplate:
    imagePullSecrets:
    - nvcrimagepullsecret
    env:
    - name: AIPERF_HTTP_CONNECTION_LIMIT
      value: '200'
    volumes:
    - name: model-cache
      persistentVolumeClaim:
        claimName: model-cache
    volumeMounts:
    - name: model-cache
      mountPath: /root/.cache/huggingface
