apiVersion: aiperf.nvidia.com/v1alpha1
kind: AIPerfJob
metadata:
  name: gpt-oss-120b-bench
spec:
  benchmark:
    models:
    - openai/gpt-oss-120b
    endpoint:
      urls:
      - http://gpt-oss-agg-frontend:8000
      type: chat
      streaming: true
      path: /v1/chat/completions
      extra:
        max_tokens: 1000
        min_tokens: 1000
        ignore_eos: true
        repetition_penalty: 1.0
        temperature: 0.0
        nvext:
          ignore_eos: true
      headers:
        Authorization: Bearer NOT USED
        Accept: text/event-stream
    tokenizer:
      name: /model-cache/hub/models--openai--gpt-oss-120b/snapshots/b5c939de8f754692c1647ca79fbf85e8c1e70f8a
    datasets:
      main:
        type: synthetic
        entries: 12800
        isl:
          mean: 128
          stddev: 0
        osl:
          mean: 1000
          stddev: 0
    warmup:
      type: concurrency
      concurrency: 3600
      requests: 3600
    profiling:
      type: concurrency
      concurrency: 3600
      requests: 36000
    random_seed: 100
  podTemplate:
    imagePullSecrets:
    - nvcrimagepullsecret
    env:
    - name: AIPERF_HTTP_CONNECTION_LIMIT
      value: '252'
    volumes:
    - name: model-cache
      persistentVolumeClaim:
        claimName: model-cache
    volumeMounts:
    - name: model-cache
      mountPath: /model-cache
