# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
"""AIPerf Kubernetes Operator module.

This module provides a kopf-based Kubernetes operator that watches for Benchmark
custom resources and orchestrates AIPerf benchmarks using JobSet.

Configuration via environment variables:
    AIPERF_OPERATOR_MONITOR_INTERVAL: Progress monitoring interval in seconds (default: 10.0)
    AIPERF_OPERATOR_MONITOR_INITIAL_DELAY: Initial delay before monitoring starts (default: 5.0)
"""

########################################################################
## 🚩                     mkinit flags                             🚩 ##
########################################################################
__ignore__ = ["logger"]
########################################################################
## ⚠️       This file is auto-generated by `make init-files`       ⚠️ ##
## ⚠️                Do not edit below this line                   ⚠️ ##
########################################################################

from aiperf.operator import events
from aiperf.operator.environment import (
    OperatorEnvironment,
)
from aiperf.operator.events import (
    EventReason,
    EventType,
    post_event,
)
from aiperf.operator.main import (
    AIPERF_GROUP,
    AIPERF_PLURAL,
    AIPERF_VERSION,
    cleanup_old_results,
    configure,
    monitor_progress,
    on_cancel,
    on_create,
    on_delete,
)
from aiperf.operator.models import (
    AIPerfJobSpec,
    EndpointConfig,
    MetricsSummary,
)
from aiperf.operator.progress_client import (
    BACKOFF_MULTIPLIER,
    INITIAL_BACKOFF_SEC,
    MAX_RETRIES,
    RETRYABLE_STATUS_CODES,
    JobProgress,
    ProgressClient,
)
from aiperf.operator.spec_converter import (
    DEFAULT_CONNECTIONS_PER_WORKER,
    AIPerfJobSpecConverter,
)
from aiperf.operator.status import (
    ConditionManager,
    ConditionType,
    Phase,
    StatusBuilder,
    format_timestamp,
    parse_timestamp,
)

__all__ = [
    "AIPERF_GROUP",
    "AIPERF_PLURAL",
    "AIPERF_VERSION",
    "AIPerfJobSpec",
    "AIPerfJobSpecConverter",
    "BACKOFF_MULTIPLIER",
    "ConditionManager",
    "ConditionType",
    "DEFAULT_CONNECTIONS_PER_WORKER",
    "EndpointConfig",
    "EventReason",
    "EventType",
    "INITIAL_BACKOFF_SEC",
    "JobProgress",
    "MAX_RETRIES",
    "MetricsSummary",
    "OperatorEnvironment",
    "Phase",
    "ProgressClient",
    "RETRYABLE_STATUS_CODES",
    "StatusBuilder",
    "cleanup_old_results",
    "configure",
    "events",
    "format_timestamp",
    "monitor_progress",
    "on_cancel",
    "on_create",
    "on_delete",
    "parse_timestamp",
    "post_event",
]
