# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
{{- if gt (int .Values.operator.replicas) 1 }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "aiperf-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "aiperf-operator.labels" . | nindent 4 }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      {{- include "aiperf-operator.selectorLabels" . | nindent 6 }}
{{- end }}
