apiVersion: aiperf.nvidia.com/v1alpha1
kind: AIPerfJob
metadata:
  name: agg-round-robin-dsv32-nvfp4-bench
spec:
  benchmark:
    models:
    - nvidia/DeepSeek-V3.2-NVFP4
    endpoint:
      urls:
      - http://agg-round-robin-dsv32-nvfp4-frontend:8000
      streaming: true
      timeout: 1000
    tokenizer:
      name: nvidia/DeepSeek-V3.2-NVFP4
    datasets:
      main:
        type: file
        path: /model-cache/traces/conversation_trace_synth_16.00x1+10.00_speedup1_maxisl110000.jsonl
        format: mooncake_trace
    warmup:
      type: concurrency
      concurrency: 4
      requests: 10
    profiling:
      type: fixed_schedule
    slos:
      time_to_first_token: 20000
      inter_token_latency: 50
    random_seed: 42
    server_metrics:
      urls:
      - http://agg-round-robin-dsv32-nvfp4-dec-0-dec-wkr:9090/metrics
      - http://agg-round-robin-dsv32-nvfp4-prefill-0:9090/metrics
    artifacts:
      records:
      - jsonl
  podTemplate:
    env:
    - name: AIPERF_HTTP_CONNECTION_LIMIT
      value: '200'
    - name: AIPERF_HTTP_SO_RCVTIMEO
      value: '120'
    volumes:
    - name: model-cache
      persistentVolumeClaim:
        claimName: model-cache
    volumeMounts:
    - name: model-cache
      mountPath: /model-cache
