# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
---
apiVersion: aiperf.nvidia.com/v1alpha1
kind: AIPerfJob
metadata:
  name: llama3-70b-disagg-sn-perf
spec:
  models:
    - RedHatAI/Llama-3.3-70B-Instruct-FP8-dynamic
  endpoint:
    urls:
      - http://llama3-70b-disagg-sn-frontend:8000
    type: chat
    path: /v1/chat/completions
    streaming: true
    extra:
      max_tokens: 1024
      min_tokens: 1024
      ignore_eos: true
      repetition_penalty: 1.0
      temperature: 0.0
      nvext:
        ignore_eos: true
    headers:
      Authorization: "Bearer NOT USED"
      Accept: text/event-stream
  datasets:
    main:
      type: synthetic
      entries: 12800
      random_seed: 100
      prompts:
        isl: {mean: 8192, stddev: 0}
        osl: {mean: 1024, stddev: 0}
  load:
    warmup:
      type: concurrency
      dataset: main
      exclude: true
      concurrency: 128
      requests: 128
    profiling:
      type: concurrency
      dataset: main
      concurrency: 128
      requests: 1280
  podTemplate:
    imagePullSecrets:
      - nvcrimagepullsecret
    env:
      - name: AIPERF_HTTP_CONNECTION_LIMIT
        value: "200"
    volumes:
      - name: model-cache
        persistentVolumeClaim:
          claimName: model-cache
    volumeMounts:
      - name: model-cache
        mountPath: /root/.cache/huggingface
