# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

from pathlib import Path
from typing import Annotated

from pydantic import Field, model_validator
from typing_extensions import Self

from aiperf.common.config.base_config import BaseConfig
from aiperf.common.config.cli_parameter import CLIParameter
from aiperf.common.config.groups import Groups
from aiperf.common.enums import ImageFormat, ImageSource


class ImageHeightConfig(BaseConfig):
    """
    A configuration class for defining image height related settings.
    """

    _CLI_GROUP = Groups.IMAGE_INPUT

    mean: Annotated[
        float,
        Field(
            default=0.0,
            ge=0,
            description="Mean height in pixels for synthetically generated images. Image heights follow a normal distribution "
            "around this mean (±`--image-height-stddev`). Used when `--image-batch-size` > 0 for multimodal vision benchmarking. "
            "Generated images are resized from source images in `assets/source_images` directory.",
        ),
        CLIParameter(
            name=(
                "--image-height-mean",  # GenAI-Perf
            ),
            group=_CLI_GROUP,
        ),
    ]

    stddev: Annotated[
        float,
        Field(
            default=0.0,
            ge=0,
            description="Standard deviation for synthetic image heights in pixels. Creates variability in vertical resolution when > 0, "
            "simulating mixed-resolution image inputs. Heights follow normal distribution. "
            "Set to 0 for uniform image heights.",
        ),
        CLIParameter(
            name=(
                "--image-height-stddev",  # GenAI-Perf
            ),
            group=_CLI_GROUP,
        ),
    ]


class ImageWidthConfig(BaseConfig):
    """
    A configuration class for defining image width related settings.
    """

    _CLI_GROUP = Groups.IMAGE_INPUT

    mean: Annotated[
        float,
        Field(
            default=0.0,
            ge=0,
            description="Mean width in pixels for synthetically generated images. Image widths follow a normal distribution "
            "around this mean (±`--image-width-stddev`). Combined with `--image-height-mean` to determine image dimensions "
            "and file sizes for multimodal benchmarking.",
        ),
        CLIParameter(
            name=(
                "--image-width-mean",  # GenAI-Perf
            ),
            group=_CLI_GROUP,
        ),
    ]

    stddev: Annotated[
        float,
        Field(
            default=0.0,
            ge=0,
            description="Standard deviation for synthetic image widths in pixels. Creates variability in horizontal resolution when > 0, "
            "simulating mixed-resolution image inputs. Widths follow normal distribution. "
            "Set to 0 for uniform image widths.",
        ),
        CLIParameter(
            name=(
                "--image-width-stddev",  # GenAI-Perf
            ),
            group=_CLI_GROUP,
        ),
    ]


class ImageConfig(BaseConfig):
    """
    A configuration class for defining image related settings.
    """

    _CLI_GROUP = Groups.IMAGE_INPUT

    width: ImageWidthConfig = ImageWidthConfig()
    height: ImageHeightConfig = ImageHeightConfig()
    batch_size: Annotated[
        int,
        Field(
            default=1,
            ge=0,
            description="Number of images to include in each multimodal request. Supported with `chat` endpoint type for vision-language models. "
            "Each image is generated by randomly sampling and resizing source images from `assets/source_images` directory to specified dimensions. "
            "Set to 0 to disable image inputs. Higher batch sizes test multi-image understanding and increase request payload size.",
        ),
        CLIParameter(
            name=(
                "--image-batch-size",
                "--batch-size-image",  # GenAI-Perf
            ),
            group=_CLI_GROUP,
        ),
    ]

    format: Annotated[
        ImageFormat,
        Field(
            default=ImageFormat.PNG,
            description="Image file format for generated images. Choose `png` for lossless compression (larger files, best quality), "
            "`jpeg` for lossy compression (smaller files, good quality), or `random` to randomly select between PNG and JPEG for each image. "
            "Format affects file size in multimodal requests and encoding overhead.",
        ),
        CLIParameter(
            name=(
                "--image-format",  # GenAI-Perf
            ),
            group=_CLI_GROUP,
        ),
    ]

    source: Annotated[
        ImageSource | Path,
        Field(
            default=ImageSource.ASSETS,
            description="Source image generation mode. `assets` loads images from the built-in `assets/source_images` directory "
            "(ships with a small set of 4 images). `noise` generates random noise images on the fly, "
            "providing a larger and more diverse pool without requiring files on disk. "
            "Noise mode is useful for stressing multimodal pipelines more realistically. "
            "A path to a directory loads images from the given directory (e.g. `--image-source ./source_images`).",
        ),
        CLIParameter(
            name=("--image-source",),
            group=_CLI_GROUP,
        ),
    ]

    @model_validator(mode="after")
    def _validate_image_options(self) -> Self:
        """Validate the image options."""
        image_options_set = {
            *self.model_fields_set,
            *self.width.model_fields_set,
            *self.height.model_fields_set,
        }
        if not self.images_enabled() and image_options_set:
            raise ValueError(
                "Image generation is disabled but image options were provided. Please set `--image-width-mean` and `--image-height-mean` to enable image generation."
            )
        return self

    def images_enabled(self) -> bool:
        """Check if images are enabled."""
        return self.width.mean > 0 and self.height.mean > 0 and self.batch_size > 0
